#when we add any comment also after that if we push code again then also actions get triggered so to avoid that we use
# git add.
# git commit -m 'Added commment in test case [skip ci]'
name: "Deploy Dist"
# on :
#     - push
#     - workflow_dispatch
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    #we need to send code to ubuntu (remote machine) for test
    steps:
      - name: Geting code...
        uses: actions/checkout@v4
      #   run: | #'|' for multiple line
      #     echo "Cloning repo ...."
      #     echo "${{toJson(github)}}"  #github provide this syntax,not yaml code
      # git clone https://github.com/${{github.repository}}.git'  #this will give repositery address
      - name: Installing Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Printing Node version
        run: node -v

      #Here we are installing similar dependency frequently like in deploy also we are installing node , so it will take more time to install , to resolve this isse we store it in cache which will store command ANd a key next time when similar command occurs it use cache memory , whenever we change package-lock.json dependency new key will generate
      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Installing dependencies
        run: npm ci #intead of npm i we use npm ci bcoz it will install the exact dependencies that are required from package-lock/json
      - name: Run test cases
        run: npm run test
  deploy:
    needs: test #this will lead to run code in sequence that's first test will run then deploy will
    runs-on: ubuntu-latest
    steps:
      - name: Geting code...
        uses: actions/checkout@v4
      - name: Installing Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Installing dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deployed Project"
